/hai/scratch/fangwu97/miniconda3/envs/sim/bin/accelerate launch \
    --config_file accelerate_configs/deepspeed_zero3.yaml \
    -m train_dpo2 \
    --dataset_name po_ready_data_10k \
    --model_name_or_path /hai/scratch/fangwu97/xu/cache/google/gemma-2-9b-it/ \
    --learning_rate 5.0e-7 \
    --beta 0.01 \
    --num_train_epochs 1 \
    --per_device_train_batch_size 4 \
    --gradient_accumulation_steps 8 \
    --gradient_checkpointing \
    --eval_strategy steps \
    --eval_steps 10 \
    --output_dir gemma-2-9b-it-DPO-10k \
    --no_remove_unused_columns \
    --max_length 2048 \
    --max_prompt_length 1800 \
    --load_best_model_at_end: True \
    --metric_for_best_model: "eval_loss" \
    --logging_steps 2 \
    --seed 42